# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 1
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"